# Generated by Django 4.2.4 on 2023-09-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('product_category', models.CharField(max_length=40)),
                ('product_image', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
                ('product_price', models.IntegerField()),
                ('product_ammount', models.IntegerField()),
            ],
        ),
    ]
