# Generated by Django 4.2.4 on 2023-09-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohine_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(upload_to='static/upload/'),
        ),
    ]
