# Generated by Django 4.2.4 on 2023-11-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohine_products', '0003_alter_products_product_ammount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('mobile', models.IntegerField(verbose_name=range(11, 14))),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
