# Generated by Django 4.2.4 on 2023-11-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohine_products', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cut_price',
            field=models.IntegerField(null=True),
        ),
    ]
