# Generated by Django 4.2.4 on 2023-11-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohine_products', '0005_products_cut_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='old_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
    ]
