# Generated by Django 4.2.4 on 2023-11-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mohine_products', '0006_products_old_price_alter_products_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='old_price',
        ),
    ]
